# Use an official Nginx image as the base
FROM nginx:latest

# Copy the built MkDocs site into the Nginx HTML directory
COPY site/ /usr/share/nginx/html/

# Expose port 80 to the host
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
